import { Course } from '../../types/lms';
import { allCurriculumCourses } from '../academics/data/courses';

export const mockCourses: Course[] = [
  {
    id: 'ci3001',
    code: 'CI3001',
    title: 'Deep Learning',
    shortDescription: 'Comprehensive study of multi-layer perceptrons, CNNs, RNNs, LSTMs, Transformers, autoencoders, and transfer learning.',
    description: 'This course focuses on the design, training, and optimization of deep neural network architectures for learning complex patterns from large-scale data. It equips students with techniques such as CNNs, RNNs, LSTMs, Transformers, and transfer learning for solving advanced AI problems in computer vision, natural language processing, speech analytics, and generative AI.',
    category: 'Computer Science & AI',
    difficulty: 'ADVANCED',
    instructorId: 'usr_tch_202',
    instructorName: 'Dr. Elena Rostova',
    instructorTitle: 'Chair of Machine Intelligence',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 68,
    durationHours: 60,
    modulesCount: 6,
    prerequisites: [
      'Machine Learning',
      'Python Programming',
      'Linear Algebra',
      'Probability and Statistics',
      'Full Stack Development',
    ],
    learningOutcomes: [
      'Explain the fundamentals of deep learning, data preparation techniques, and deep learning frameworks for building intelligent systems.',
      'Apply perceptron and neural network architectures, activation functions, and backpropagation algorithms for solving classification problems.',
      'Examine sequential data using RNN, LSTM, and GRU architectures for prediction and classification tasks.',
      'Analyze the architecture, components, and performance of convolutional neural network models for image processing and computer vision applications.',
      'Apply advanced deep learning architectures and optimization techniques to solve complex learning problems across diverse application domains.',
      'Implement deep learning solutions for real-world applications involving image, text, audio, video, and numerical data.',
    ],
    progress: 68,
    rating: 4.95,
    lastUpdated: '2026-09-10',
    isEnrolled: true,
  },
  {
    id: 'ci3202',
    code: 'CI3202',
    title: 'Operating System',
    shortDescription: 'Process scheduling, concurrency, synchronization, deadlocks, virtual memory management, Linux kernel internals, and Android OS.',
    description: 'The Operating System is a core subject that provides fundamental knowledge about how computer systems manage hardware and software resources efficiently. It explains key concepts such as process scheduling, memory management, file systems, and inter-process communication.',
    category: 'Systems & Infrastructure',
    difficulty: 'INTERMEDIATE',
    instructorId: 'usr_tch_205',
    instructorName: 'Prof. Marcus Vance',
    instructorTitle: 'Associate Professor of Cloud & Systems Engineering',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 74,
    durationHours: 48,
    modulesCount: 6,
    prerequisites: [
      'C/C++ Programming',
      'Data Structures',
      'Computer Organization and Architecture',
    ],
    learningOutcomes: [
      'Describe OS basic structures and functions.',
      'Explain about processes and do the detail analysis of different Scheduling strategies.',
      'Demonstrate process synchronization strategies and deadlock prevention.',
      'Compare and contrast various memory management schemes and demand paging.',
      'Exhibit the file handling and IO activities at OS level.',
      'Analyze Linux kernel components and Android system architecture.',
    ],
    progress: 54,
    rating: 4.8,
    lastUpdated: '2026-09-08',
    isEnrolled: true,
  },
  {
    id: 'ci3003d',
    code: 'CI3003D',
    title: 'MLOPS',
    shortDescription: 'End-to-end ML lifecycle, DVC data versioning, MLflow experiment tracking, Airflow pipeline automation, FastAPI/Docker deployment, and SageMaker.',
    description: 'Machine Learning Operations (MLOps) is an essential discipline that bridges the gap between machine learning model development and real-world deployment. It combines Machine Learning, DevOps, and Cloud Computing practices to automate, deploy, monitor, and maintain AI systems efficiently.',
    category: 'Computer Science & AI',
    difficulty: 'ADVANCED',
    instructorId: 'usr_tch_208',
    instructorName: 'Dr. Sarah Lin',
    instructorTitle: 'Associate Professor of Applied AI & DevOps',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 58,
    durationHours: 54,
    modulesCount: 6,
    prerequisites: [
      'Programming Fundamentals and Python',
      'Basics of Machine Learning',
      'Introduction to Cloud and DevOps Concepts',
    ],
    learningOutcomes: [
      'Explain the key differences between software development and ML lifecycles.',
      'Apply MLOps tools like MLflow, DVC in reproducible workflows.',
      'Manage data, features, and experiments effectively.',
      'Automate ML pipelines using CI/CD integration.',
      'Deploy and monitor ML models with Docker, FastAPI, and Prometheus.',
      'Implement responsible AI practices, ensuring fairness, privacy, and compliance.',
    ],
    progress: 42,
    rating: 4.9,
    lastUpdated: '2026-09-09',
    isEnrolled: true,
  },
  {
    id: 'ci3203b',
    code: 'CI3203B',
    title: 'Distributed and Federated Learning',
    shortDescription: 'Decentralized AI, FedAvg algorithm, horizontal/vertical federated learning, differential privacy, TensorFlow Federated, and Flower.',
    description: 'This course provides an in-depth understanding of distributed machine learning algorithms, parallel model training, and federated optimization techniques for large-scale AI systems. Students learn data-parallel and model-parallel training strategies, distributed gradient descent, parameter server architectures, and privacy-preserving collaborative learning.',
    category: 'Computer Science & AI',
    difficulty: 'ADVANCED',
    instructorId: 'usr_tch_210',
    instructorName: 'Prof. Kenji Takahashi',
    instructorTitle: 'Director of Distributed Intelligent Systems',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 46,
    durationHours: 48,
    modulesCount: 6,
    prerequisites: ['Machine Learning'],
    learningOutcomes: [
      'Describe the key concepts and architecture of Federated Learning.',
      'Apply different methods and models to develop federated learning systems.',
      'Apply optimization techniques in Federated Learning (FedAvg, Fed+).',
      'Construct and scale a simple federated system considering privacy and security measures.',
      'Understand system architectures used in intelligent systems (TFF, Flower, PySyft).',
      'Apply communication strategies for distributed systems.',
    ],
    progress: 30,
    rating: 4.88,
    lastUpdated: '2026-09-11',
    isEnrolled: true,
  },
  {
    id: 'ci3203a',
    code: 'CI3203A',
    title: 'Ethical and Responsible AI',
    shortDescription: 'Algorithmic fairness, bias mitigation, explainable AI (SHAP/LIME), privacy-preserving ML, AI lifecycle governance, and GDPR/NITI Aayog compliance.',
    description: 'This course focuses on the technical foundations of trustworthy AI, including algorithmic fairness, bias quantification and mitigation, explainable AI (XAI), model interpretability, robustness, and privacy-preserving machine learning. Students learn methods for fairness evaluation, adversarial robustness testing, differential privacy, federated learning, and AI governance mechanisms.',
    category: 'Computer Science & AI',
    difficulty: 'INTERMEDIATE',
    instructorId: 'usr_tch_215',
    instructorName: 'Dr. Aris Thorne',
    instructorTitle: 'Chair of Responsible AI Ethics',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 60,
    durationHours: 48,
    modulesCount: 6,
    prerequisites: [
      'Programming Fundamentals and Python',
      'Basics of Machine Learning/Deep Learning/Natural Language Processing',
    ],
    learningOutcomes: [
      'Explain the concepts, ethical principles, and societal implications of Artificial Intelligence and Responsible AI.',
      'Analyze AI systems for fairness, bias, transparency, explainability, and accountability using appropriate ethical frameworks.',
      'Evaluate privacy, security, trustworthiness, and governance issues associated with AI applications and data-driven systems.',
      'Apply responsible AI principles, risk assessment methods, and regulatory guidelines in the design and deployment of AI solutions.',
      'Develop human-centered, inclusive, and sustainable AI solutions that address societal and organizational challenges responsibly.',
      'Assess emerging ethical challenges related to Generative AI, Large Language Models, autonomous systems, and global AI governance.',
    ],
    progress: 60,
    rating: 4.92,
    lastUpdated: '2026-09-07',
    isEnrolled: true,
  },
  {
    id: 'ci3203c',
    code: 'CI3203C',
    title: 'Information Security',
    shortDescription: 'Cryptography (AES, RSA, ECC), network security, ethical hacking, vulnerability scanning (Nmap, Nessus, Wireshark), and cyber laws.',
    description: 'This course provides the fundamentals of information security, including cryptography, network and system security, secure authentication, and vulnerability assessment. It equips students with practical knowledge of ethical hacking, cyber defense, and emerging security technologies such as cloud, IoT, blockchain, and AI security.',
    category: 'Systems & Infrastructure',
    difficulty: 'ADVANCED',
    instructorId: 'usr_tch_205',
    instructorName: 'Prof. Marcus Vance',
    instructorTitle: 'Associate Professor of Cloud & Cybersecurity',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 52,
    durationHours: 54,
    modulesCount: 6,
    prerequisites: [
      'Basic knowledge of Computer Networks',
      'Operating Systems',
      'Programming concepts',
    ],
    learningOutcomes: [
      'Explain concepts of information security and cyber threats.',
      'Apply cryptographic techniques for secure communication.',
      'Analyse network and system security mechanisms.',
      'Perform vulnerability assessment using security tools.',
      'Evaluate cyber laws and emerging trends.',
      'Design and recommend secure computing solutions by integrating modern security technologies, cyber laws, and best security practices.',
    ],
    progress: 35,
    rating: 4.85,
    lastUpdated: '2026-09-06',
    isEnrolled: true,
  },
  {
    id: 'mdm3_at',
    code: 'MDM3',
    title: 'Automata Theory',
    shortDescription: 'Finite automata (DFA/NFA), regular expressions, context-free grammars (CFG), pushdown automata (PDA), Turing machines, and NP-completeness.',
    description: 'This course provides a rigorous mathematical foundation of computation through formal models such as Deterministic and Non-Deterministic Finite Automata (DFA/NFA), Pushdown Automata (PDA), and Turing Machines. It covers language classification under the Chomsky hierarchy, regular languages, context-free languages, closure properties, and complexity of problems.',
    category: 'Mathematics',
    difficulty: 'ADVANCED',
    instructorId: 'usr_tch_208',
    instructorName: 'Dr. Sarah Lin',
    instructorTitle: 'Professor of Pure & Applied Mathematics',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 48,
    durationHours: 36,
    modulesCount: 6,
    prerequisites: ['Discrete Mathematics'],
    learningOutcomes: [
      'Understand formal language, translation logic, essentials of translation, alphabets, language representation and apply it to design Finite Automata and its variants.',
      'Construct regular expression to present regular language and understand pumping lemma for RE.',
      'Design Context Free Grammars and learn to simplify the grammar.',
      'Construct Pushdown Automaton model for the Context Free Language.',
      'Design Turing Machine for the different requirements outlined by theoretical computer science.',
      'Understand different classes of problems, classify and analyze them and study concepts of NP completeness.',
    ],
    progress: 50,
    rating: 4.75,
    lastUpdated: '2026-09-04',
    isEnrolled: true,
  },
  {
    id: 'mdm3_dt',
    code: 'MM0901B',
    title: 'Design Thinking and Product Lifecycle Management (PLM)',
    shortDescription: 'Human-centered design, AI in product ideation, MVP canvas, agile sprint planning in Jira, CI/CD, testing (UAT), and product analytics.',
    description: 'The Design Thinking Product Lifecycle Management (PDLC) course is highly relevant for Artificial Intelligence and Engineering students as it provides practical knowledge of transforming innovative ideas into real-world products. The course integrates Design Thinking, AI-assisted development, Agile methodologies, testing, deployment, and industrial case studies.',
    category: 'Entrepreneurship & Leadership',
    difficulty: 'INTERMEDIATE',
    instructorId: 'usr_tch_220',
    instructorName: 'Sarah Sterling, MBA',
    instructorTitle: 'Director of Shreenil Venture Studio & Product Management',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 65,
    durationHours: 36,
    modulesCount: 6,
    prerequisites: [
      'Students should have basic knowledge of programming, software engineering, and fundamentals of AI',
      'Familiarity with problem-solving techniques and basic application development concepts',
    ],
    learningOutcomes: [
      'Apply Design Thinking principles to identify user-centric problems and develop innovative product ideas.',
      'Design AI-assisted product plans, user journeys, prototypes, and Minimum Viable Products (MVPs).',
      'Explain and analyze various stages of the Product Development Life Cycle (PDLC) and product planning methodologies.',
      'Compare, evaluate, and select suitable product development models such as Agile, Waterfall, Spiral, Prototype, and DevOps.',
      'Apply testing, quality assurance, deployment, and maintenance techniques for reliable product development.',
      'Analyze the role of Artificial Intelligence in PDLC through real-world industrial case studies and practical applications.',
    ],
    progress: 72,
    rating: 4.9,
    lastUpdated: '2026-09-05',
    isEnrolled: true,
  },
  {
    id: 'ci4001',
    code: 'CI4001',
    title: 'Generative AI',
    shortDescription: 'Evolution of Generative AI models (GANs, VAEs, Diffusion), advanced NLP, Transformers, LLMs (GPT/BERT), and RAG systems.',
    description: 'To introduce the foundational concepts and evolution of Generative AI models such as GANs, VAEs, and Diffusion models. Explore sequence modeling using RNNs, LSTMs, Attention Mechanism, Transformers, and Large Language Models with prompt engineering and RAG.',
    category: 'Computer Science & AI',
    difficulty: 'ADVANCED',
    instructorId: 'usr_tch_202',
    instructorName: 'Dr. Elena Rostova',
    instructorTitle: 'Chair of Machine Intelligence',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 42,
    durationHours: 32,
    modulesCount: 6,
    prerequisites: ['Python', 'Basic ML', 'Linear Algebra', 'Neural Networks'],
    learningOutcomes: [
      'Explain the foundational concepts and evolution of Generative AI models.',
      'Apply natural language processing techniques for text classification and sentiment analysis.',
      'Design sequence models using RNNs, LSTMs, and GRUs.',
      'Implement transformer models and prompt engineering strategies for LLMs.',
    ],
    progress: 25,
    rating: 4.95,
    lastUpdated: '2026-09-11',
    isEnrolled: false,
  },
  {
    id: 'ci4005',
    code: 'CI4005',
    title: 'Natural Language Processing',
    shortDescription: 'Morphological parsing, regular expressions, CFGs, syntactic analysis, machine translation, and information retrieval.',
    description: 'Although Natural Language Processing (NLP) has been with us for quite some time, it has only recently gained industry-wide attention, thanks to Deep Learning. Today, NLP is a core competence area in Data Science and IT, with applications spanning across sectors.',
    category: 'Computer Science & AI',
    difficulty: 'ADVANCED',
    instructorId: 'usr_tch_202',
    instructorName: 'Dr. Elena Rostova',
    instructorTitle: 'Chair of Machine Intelligence',
    status: 'PUBLISHED',
    visibility: 'PUBLIC',
    startDate: '2026-08-01',
    endDate: '2026-12-15',
    enrolledStudentsCount: 38,
    durationHours: 32,
    modulesCount: 6,
    prerequisites: ['Theory of Computer Science', 'Compiler Design'],
    learningOutcomes: [
      'Interpret morphology for given natural language.',
      'Construct shallow depth lexical analyzer and syntactic analyzer for given natural language.',
      'Develop shallow depth type dependency parser for given natural language.',
      'Develop shallow depth machine transliteration, machine translation, information retrieval for given natural language.',
      'Correlate shallow depth machine transliteration, machine translation, information for given natural language.',
      'Evaluate machine transliteration, machine translation and information retrieval results using standard evaluation metrics.',
    ],
    progress: 15,
    rating: 4.88,
    lastUpdated: '2026-09-10',
    isEnrolled: false,
  },
];
