import { Quiz } from '../../types/lms';

export const mockQuizzes: Quiz[] = [
  {
    id: 'quiz-101',
    courseId: 'ci3001',
    courseCode: 'CI3001',
    courseTitle: 'Deep Learning',
    title: 'Quiz 1: Unit I & II — Deep Learning Fundamentals & Perceptron Diagnostics',
    description: 'Assess mathematical grasp of activation functions, forward/backward propagation, XOR problem, and loss function optimization.',
    instructions: 'Please answer all questions within the allocated time. You may navigate freely between questions. Once submitted, answers cannot be altered.',
    timeLimitMinutes: 15,
    maxAttempts: 2,
    passingScorePercent: 75,
    questionsCount: 5,
    totalMarks: 25,
    userAttemptsCount: 1,
    bestScore: 23,
    questions: [
      {
        id: 'q-1',
        type: 'MCQ',
        prompt: 'Which of the following activation functions exhibits non-saturation for all positive pre-activations, avoiding gradient vanishing for positive inputs?',
        options: [
          'Sigmoid function',
          'Hyperbolic Tangent (Tanh)',
          'Rectified Linear Unit (ReLU)',
          'Softmax function',
        ],
        correctOptionIndex: 2,
        marks: 5,
        explanation: 'ReLU is defined as f(x) = max(0, x). For all x > 0, its derivative is constant (1.0), which prevents gradient saturation.',
      },
      {
        id: 'q-2',
        type: 'TRUE_FALSE',
        prompt: 'A single-layer perceptron with a linear decision boundary cannot solve the non-linear XOR classification problem without adding hidden layer representations or non-linear projections.',
        options: ['True', 'False'],
        correctOptionIndex: 0,
        marks: 5,
        explanation: 'True. Minsky and Papert proved in 1969 that single-layer perceptrons can only classify linearly separable patterns, making multi-layer perceptrons necessary for XOR.',
      },
      {
        id: 'q-3',
        type: 'MCQ',
        prompt: 'In backpropagation, how is the gradient of the scalar loss with respect to weight matrix W computed given upstream activation gradient and input vector?',
        options: [
          'Direct element-wise inversion',
          'Outer product of error term (dL/dz) and transposed input activation',
          'Scalar subtraction of learning rate',
          'Matrix determinant projection',
        ],
        correctOptionIndex: 1,
        marks: 5,
        explanation: 'By application of the multivariate chain rule, dL/dW = (dL/dz) * a^T.',
      },
      {
        id: 'q-4',
        type: 'MCQ',
        prompt: 'Which technique is explicitly utilized in deep learning to prevent overfitting by penalizing large weight coefficients?',
        options: [
          'L2 Regularization (Weight Decay)',
          'Softmax normalization',
          'Forward inference',
          'One-hot encoding',
        ],
        correctOptionIndex: 0,
        marks: 5,
        explanation: 'L2 regularization adds a penalty term proportional to the square of the magnitude of coefficients to the loss function.',
      },
      {
        id: 'q-5',
        type: 'SHORT_ANSWER',
        prompt: 'What term describes the training scenario where a neural network performs exceptionally well on training data but fails to generalize to validation data?',
        marks: 5,
        explanation: 'Overfitting occurs when the model memorizes noise and idiosyncrasies in the training corpus.',
      },
    ],
  },
  {
    id: 'quiz-201',
    courseId: 'ci3001',
    courseCode: 'CI3001',
    courseTitle: 'Deep Learning',
    title: 'Quiz 2: Unit IV — CNN Architectures, Kernels & Hyperparameters',
    description: 'Check understanding of receptive fields, pooling layers, stride/padding calculations, and popular architectures (AlexNet, VGG, ResNet).',
    instructions: 'Timed assessment (20 minutes). Complete all 4 questions before time expires.',
    timeLimitMinutes: 20,
    maxAttempts: 2,
    passingScorePercent: 70,
    questionsCount: 4,
    totalMarks: 20,
    questions: [
      {
        id: 'q-201-1',
        type: 'MCQ',
        prompt: 'If an input feature map has dimensions 32x32 and is convolved with a 5x5 filter with stride=1 and padding=0, what is the spatial dimension of the output map?',
        options: ['28x28', '30x30', '32x32', '27x27'],
        correctOptionIndex: 0,
        marks: 5,
        explanation: 'Formula: Output = ((Input - Kernel + 2*Padding) / Stride) + 1 = ((32 - 5 + 0) / 1) + 1 = 28.',
      },
      {
        id: 'q-201-2',
        type: 'TRUE_FALSE',
        prompt: 'Standard 2D Convolution layers are strictly equivariant to spatial translations, meaning shifting an input image produces an identically shifted feature map.',
        options: ['True', 'False'],
        correctOptionIndex: 0,
        marks: 5,
        explanation: 'True. Weight sharing across the grid provides translation equivariance.',
      },
      {
        id: 'q-201-3',
        type: 'MCQ',
        prompt: 'Why do Residual Networks (ResNet) mitigate the vanishing gradient problem during deep backpropagation?',
        options: [
          'They replace matrix multiplication with scalar addition in all layers',
          'The identity skip connection allows gradients to flow directly through addition gates with a derivative term of +1',
          'They eliminate non-linear activation functions completely',
          'They enforce orthogonal weight matrices',
        ],
        correctOptionIndex: 1,
        marks: 5,
        explanation: 'Gradient of y = F(x) + x with respect to x is dF/dx + I. The +I ensures the gradient does not disappear even when dF/dx is small.',
      },
      {
        id: 'q-201-4',
        type: 'SHORT_ANSWER',
        prompt: 'What is the primary computational benefit of 1x1 convolutions introduced in Network-in-Network and Inception architectures?',
        marks: 5,
        explanation: 'Channel-dimension reduction/projection and cross-channel pooling without altering spatial dimensions, dramatically reducing subsequent filter parameters.',
      },
    ],
  },
];
